In [20]:
from scipy.optimize import minimize
import pandas as pd
import numpy as np


In [49]:
# Carregando os dados para a variável "data"
data = pd.read_csv("../datasets/ex2data1.txt", header = None, names = ["Avaliacao 1", "Avaliacao 2", "Aprovado"])

# Inicializando Variáveis
m = len(data["Aprovado"])

x0 = np.ones(m)
avaliacao_1 = np.array((data["Avaliacao 1"]))
avaliacao_2 = np.array((data["Avaliacao 2"]))

X = np.array([x0, avaliacao_1, avaliacao_2]).T
y = np.array(data["Aprovado"]).reshape((m,1))
m, n = X.shape

print("Matriz X:\n",X[:5])
print("\n\nDados brutos: ")
data.head()

Matriz X:
 [[ 1.         34.62365962 78.02469282]
 [ 1.         30.28671077 43.89499752]
 [ 1.         35.84740877 72.90219803]
 [ 1.         60.18259939 86.3085521 ]
 [ 1.         79.03273605 75.34437644]]


Dados brutos: 


Avaliacao 1  Avaliacao 2  Aprovado
0    34.623660    78.024693         0
1    30.286711    43.894998         0
2    35.847409    72.902198         0
3    60.182599    86.308552         1
4    79.032736    75.344376         1

In [59]:


def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def custo(theta, X, y):
    m = len(y)
    h = sigmoid(np.dot(X, theta))
    custo = (1 / m) * np.sum(-y * np.log(h + 1e-15) - (1 - y) * np.log(1 - h + 1e-15))
    return custo

def gradiente(theta, X, y):
    m = len(y)
    h = sigmoid(np.dot(X, theta))
    erro = h - y
    grad = (1 / m) * np.dot(X.T, erro)
    return grad

# Exemplo de uso com dimensão 3x100
X = np.random.rand(100, 3)  # matriz de características (3 x 100)
y = np.random.randint(0, 2, size=(100, 1))  # vetor de classes (1 x 100)
theta = np.zeros(3)  # parâmetros do modelo (incluindo o termo de viés)

resultado = minimize(custo, theta, args=(X, y.ravel()), method='CG', jac=gradiente)

x_otimo = resultado.x
custo_minimo = resultado.fun
sucesso = resultado.success

print("Parâmetros ótimos:", x_otimo)
print("Custo mínimo:", custo_minimo)
print("Sucesso:", sucesso)


Parâmetros ótimos: [ 0.70085899 -0.0456115  -1.09551791]
Custo mínimo: 0.6750231451024586
Sucesso: True


In [43]:
x0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
y.ravel().ravel().ravel()

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64)